from rest_framework_simplejwt.views import TokenObtainPairView
from .serializers import TicketingTokenObtainPairSerializer


class TicketingTokenObtainPairView(TokenObtainPairView):
    serializer_class = TicketingTokenObtainPairSerializer